### ISSUE TITLE
Cannot resolve symbol 'Configs'

### ISSUE THREAD

**Issue by ysnsyhn** [ItzNotABug/AppOpenAdManager#8]
I tried it from the documentation and the example codes but I got this error.

Cannot resolve symbol 'Configs'

how to solve this issue?

**Comment by Fonceur** [comment]
That's because the version pulled by Gradle is older than the current master branch, so the instructions don't match...

**Comment by ItzNotABug** [comment]
This issue is fixed now as the latest 1.8.2 is released on mavenCentral & the ReadMe also reflects the same.
